# Base image to build from
FROM node:20-alpine

# Main directory to use
WORKDIR /app

# Copy required files across
COPY . .

# Install node packages, install serve, build the app, and remove dependencies at the end
RUN npm install

# Expose port
EXPOSE 3000

# Start the app using node
CMD ["node", "./src/server.js"]
