# Base image to build from
FROM node:20-alpine

# Main directory to use
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy remaining app files
COPY ./src ./src
COPY swagger.yaml ./
COPY cheeses.json ./

# Expose port
EXPOSE 3000

# Start the app using node
CMD ["npm", "start"]
