openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple Cheese API
  description: Displays cheese for a simple cheeseria POC app

  # Basic security
security:
  - BasicAuth: []
  
# API paths
paths: 


  # All Cheeses
  /cheeses:
    get:
      description: Returns a list of cheeses
      responses:
        '200':
          description: Successfully returned a list of cheese
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cheese'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

  # All Cheeses
  /cheese/:id:
    get:
      description: Returns a single cheese
      parameters:
        - name: cheese_id
          in: query
          description: ID of the cheese to get
          schema:
            type: integer
      responses:
        '200':
          description: Successfully found and returned a cheese
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheese'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
 
# Components
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  # Global schema for cheese definition
  schemas:
    Cheese:
      type: object
      properties:
        cheese_id:
          type: integer
        cheese_name:
          type: string
        cheese_origin:
          type: string
        cheese_price:
          type: integer
        cheese_colour:
          type: string
        cheese_texture:
          type: string
        cheese_milk:
          type: string
        cheese_photo:
          type: string

