openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple Cheese API
  description: Displays cheese for a simple cheeseria POC app

  # Basic security
security:
  - BasicAuth: []
  
# API paths
paths: 

  # All Cheeses
  /cheeses:
    get:
      description: Returns a list of cheeses
      responses:
        "200":
          description: Successfully returned a list of cheese
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cheese'

    post:
      description: Add a new cheese to the list of cheeses
      requestBody:
        description: The cheese data to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cheese'
      responses:
        "201":
          description: Successfully added new cheese
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheese'
        "400":
          description: Invalid input

    # Individual cheese
  /cheeses/{id}:
    get:
      description: Returns a single cheese
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the cheese to get
          schema:
            type: integer
            minimum: 1

      responses:
        "200":
          description: Successfully found and returned a cheese
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheese'
        "400":
          description: Invalid cheese ID specified
        "404":
          description: No cheese with the specified ID was found
        default:
          description: Unexpected error

    put:
      description: Update cheese data in the list of cheeses
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the cheese to get
          schema:
            type: integer
            minimum: 1
            
      requestBody:
        description: The cheese data to overwrite with
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cheese'
      responses:
        "201":
          description: Successfully updated cheese data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cheese'
        "400":
          description: Invalid cheese ID specified
        "404":
          description: No cheese with the specified ID was found
        default:
          description: Unexpected error
 
# Components
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  # Global schema for cheese definition
  schemas:
    Cheese:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        origin:
          type: string
        price:
          type: integer
        colour:
          type: string
        texture:
          type: string
        milk:
          type: string
        photo:
          type: string

